application: riddhithakkarportfolio
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
  
- url: /details.html
  static_files: public/details.html
  upload: public/details.html



- url: /
  static_files: public/index.html
  upload: public/index.html